services:
  nettunnel.udptrafficgenerator:
    image: ${DOCKER_REGISTRY-}nettunneludptrafficgenerator
    profiles: [client-test]
    network_mode: "host"
    build:
      context: ..
      dockerfile: src/NetTunnel.UdpTrafficGenerator/Dockerfile
    environment:
      TraficGeneratorSettings__ListenPort: 4000
      TraficGeneratorSettings__TargetHost: nettunnel.client-tunnelnode
      TraficGeneratorSettings__TargetPort: 5000


  nettunnel.client-tunnelnode:
    image: ${DOCKER_REGISTRY-}nettunneltunnelnode
    profiles: [client, client-test]
    network_mode: "host"
    build:
      context: ..
      dockerfile: src/NetTunnel.TunnelNode/Dockerfile
    environment:
      TunnelNodeSettings__ExternalListenPort: 5000
      TunnelNodeSettings__ExternalTargetHost: nettunnel.udptrafficgenerator
      TunnelNodeSettings__ExternalTargetPort: 4000

      TunnelNodeSettings__TunnelListenPort: 5100
      TunnelNodeSettings__TunnelTargetHost: nettunnel.server-tunnelnode
      TunnelNodeSettings__TunnelTargetPort: 6100


  nettunnel.server-tunnelnode:
    image: ${DOCKER_REGISTRY-}nettunneltunnelnode
    profiles: [server, server-test]
    network_mode: "host"
    build:
      context: ..
      dockerfile: src/NetTunnel.TunnelNode/Dockerfile
    environment:
      TunnelNodeSettings__TunnelListenPort: 6100
      TunnelNodeSettings__TunnelTargetHost: nettunnel.client-tunnelnode
      TunnelNodeSettings__TunnelTargetPort: 5100

      TunnelNodeSettings__ExternalListenPort: 6000
      TunnelNodeSettings__ExternalTargetHost: nettunnel.udpechoserver
      TunnelNodeSettings__ExternalTargetPort: 7000


  nettunnel.udpechoserver:
    image: ${DOCKER_REGISTRY-}nettunneludpechoserver
    profiles: [server-test]
    network_mode: "host"
    build:
      context: ..
      dockerfile: src/NetTunnel.UdpEchoServer/Dockerfile
    environment:
      UdpEchoServerSettings__ListenPort: 7000



