services:
  nettunnel.udptrafficgenerator:
    image: ${DOCKER_REGISTRY-}nettunneludptrafficgenerator
    profiles: [client]
    build:
      context: ..
      dockerfile: src/NetTunnel.UdpTrafficGenerator/Dockerfile
    networks:
      net-tunnel-network:
        ipv4_address: 10.0.0.2


  nettunnel.tunnelclient:
    image: ${DOCKER_REGISTRY-}nettunneltunnelclient
    profiles: [client]
    build:
      context: ..
      dockerfile: src/NetTunnel.TunnelClient/Dockerfile
    networks:
      net-tunnel-network:
        ipv4_address: 10.0.0.3

  nettunnel.tunnelserver:
    image: ${DOCKER_REGISTRY-}nettunneltunnelserver
    profiles: [server]
    build:
      context: ..
      dockerfile: src/NetTunnel.TunnelServer/Dockerfile
    ports:
      - 5555:5555/udp
    networks:
      net-tunnel-network:
        ipv4_address: 10.0.0.4


  nettunnel.udpechoserver:
    image: ${DOCKER_REGISTRY-}nettunneludpechoserver
    profiles: [server]
    build:
      context: ..
      dockerfile: src/NetTunnel.UdpEchoServer/Dockerfile
    networks:
      net-tunnel-network:
        ipv4_address: 10.0.0.5


networks:
  net-tunnel-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29


